sudo: required
language: c++
dist: bionic

# services:
#   - docker
  
os:
  - linux
compiler:
  - clang
  - gcc
before_install:
  # - |
  #   if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
  #     sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y \
  #     && sudo apt-get update -qq \
  #     && if [ "$CXX" == "g++" ]; then
  #       sudo apt-get install -qq g++-4.7 && export CXX="g++-4.7" CC="gcc-4.7"
  #     fi
  #   fi
  # - docker pull centos/devtoolset-7-toolchain-centos7
  # - mkdir testdocker
  # - docker run -v testdocker:/tmp/test/  centos/devtoolset-7-toolchain-centos7 "ls / > /tmp/test/"
  # - ls testdocker/*
  - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake  g++-multilib 

before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - make
  - ./testt

matrix:
  exclude:
  - os: linux
    compiler: clang
